### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by phillipPhillip** [gloomyson/StarCraft#11]
Im new and I cant seem to access this?

**Comment by gloomyson** [comment]
Double click index.html is OK, but your web browser should be modern one, suggest using Chrome, Firefox, Opera and IE11

**Comment by josephmilla** [comment]
Just open `index.html`, you should be good to go. +1 for using Chrome

@gloomyson, I just want to say this is a very impressive project. I'll take a look at the codebase a little closer later this week. :wink:

**Comment by phillipPhillip** [comment]
double clicking index.html gets me here ?

https://github.com/gloomyson/StarCraft/blob/master/index.html

**Comment by phillipPhillip** [comment]
https://github.com/gloomyson/StarCraft/index.html 404 ...?

**Comment by starthal** [comment]
Clone the repo and open `index.html` from your local directory.

**Comment by coolking70** [comment]
You shall just click download ZIP button on the right of the main page，unzip it and double click the index.html.
Or you can just try it on my website(may be closed at anytime):http://ck70.net/sc/

**Comment by phillipPhillip** [comment]
opens yet too slow for play on your website...

**Comment by phillipPhillip** [comment]
how may I get involved to and or create a multiplayer capability...

**Comment by phillipPhillip** [comment]
http://ck70.net/index.html you will add a tree of links of your website

**Comment by phillipPhillip** [comment]
Chrome....very slow...not usable yet...

**Comment by lun471k** [comment]
The fact that it is slow on your machine does not mean it is slow on someone else's machine... Game is running just fine here.

**Comment by remram44** [comment]
Or you can just use rawgit: http://cdn.rawgit.com/gloomyson/StarCraft/master/index.html

**Comment by phillipPhillip** [comment]
yes, it is still slow however works a little viz raw...thank you to both,
hot keys?

**Comment by CKing** [comment]
*crossposting*
running on [my](http://sc.paars-gaming.de/) server, git pull is on a weekly cron.
have fun!

**Comment by phillipPhillip** [comment]
please someone multiplayer

**Comment by lun471k** [comment]
Multiplayer has not been implemented yet.

**Comment by phillipPhillip** [comment]
very nice

**Comment by omnidan** [comment]
I added a short guide to make it easier to get started with the game even if you have never seen github before: https://github.com/gloomyson/StarCraft/pull/17

**Comment by bendavis78** [comment]
You should just make a gh-pages branch and host it here on github: https://help.github.com/articles/creating-project-pages-manually/

**Comment by phillipPhillip** [comment]
level 1 is impossible...?

**Comment by zethussuen** [comment]
dear lord this thread is fucking gold :+1:

**Comment by remram44** [comment]
Someone here has no clue what is going on or even what GitHub is...

**Comment by xboi209** [comment]
^
