### ISSUE TITLE
can't seem to mine minerals

### ISSUE THREAD

**Issue by smergler** [gloomyson/StarCraft#18]
In level 7 I was able to make a drone, but I was not able to mine any minerals.  

However, good job!!

**Comment by xboi209** [comment]
The "map" is currently just a picture of the whole map which includes the minerals, so they're just static content for now

**Comment by solio** [comment]
So I think we should set a timer that make player's mine increasing.

**Comment by xboi209** [comment]
@solio What do you mean? Mining should the same as the original game.

**Comment by gloomyson** [comment]
I'll add mining later, currently you can use cheat "show me the money" instead.
