### ISSUE TITLE
Finishing a mission freezes the game on the winning screen.

### ISSUE THREAD

**Issue by YGrancharov** [gloomyson/StarCraft#2]
Upon successfully completing a mission, the screen freezes on the winning screen and you can no longer navigate back or forth to other mission. Thus you are required to reload and start over.

**Comment by gloomyson** [comment]
I'm sorry but it's normal case, because what after winning screen like scorecard or back button have not been done yet, this game is not finished by now

**Comment by boynet** [comment]
I also got confuse, the version got me beliving its somehow complete

**Comment by gloomyson** [comment]
The version means basic features complete, not all the details
