### ISSUE TITLE
Put the URL http://gloomyson.github.io/StarCraft/ in README.md

### ISSUE THREAD

**Issue by ngosang** [gloomyson/StarCraft#23]
Put the URL http://gloomyson.github.io/StarCraft/ in README.md

**Comment by gloomyson** [comment]
Already added into readme, but code is not as latest as main branch, what shall I do?

**Comment by ngosang** [comment]
There are 2 branches in GitGub: master and gh-pages. You should put the maser content in gh-pages.

**Comment by gloomyson** [comment]
How can I put master content into gh-pages branch? I always submit code directly to main branch by Github client

**Comment by ngosang** [comment]
I use the git tool in the command line, I can't help you. :disappointed:

**Comment by gloomyson** [comment]
Fixed in 9ce1825
