### ISSUE TITLE
Two zerglings cost 25 minerals

### ISSUE THREAD

**Issue by fadimko** [gloomyson/StarCraft#5]
![](http://i.imgur.com/0b201ve.png)
![](http://i.imgur.com/MaodaTX.png)

**Comment by ThePhoenixBird** [comment]
this is not an issue, that behavior is exactly as the original game, from a single larvae it spawns 2 zerglins for 25 minerals cost, and it only occupy 1 population

source: http://starcraft.wikia.com/wiki/Zergling_(StarCraft)

**Comment by fadimko** [comment]
@ThePhoenixBird Sorry for the question, but did you play SC? :) Couple of zerglings always costed 50 minerals

**Comment by xboi209** [comment]
Each zergling is *worth* 25 minerals and .5 population, but building zerglings should cost 50 minerals and 1 population.

**Comment by gloomyson** [comment]
Thanks fadimko, maybe you guys can help me find some bugs in my game, just try cheat code "show me the money" and you can get enough resources to try other units and upgrades

**Comment by gloomyson** [comment]
If you want to add any units or buildings, just F12 to call developer tool out, input javascript like "new Zerg.Zergling({x:100,y:100})", the parameter x,y mean initial location, to add an enemy, add isEnemy:true, to remove fog: "Map.fogFlag=false" and so on.

**Comment by ThePhoenixBird** [comment]
@fadimko this is classic Starcraft, so Zerglings cost 25, from Broodwar onwards with balance patches they cost 50 minerals.

So its up to the developer to abide to those post-release game balances, im up for it.

**Comment by xboi209** [comment]
@ThePhoenixBird No this is StarCraft: Brood War as you can see with [this picture that has a Zerg Devourer in it](https://raw.githubusercontent.com/gloomyson/StarCraft/master/img/Demo/Demo.jpg).

Also there were no patches that affected the cost of Zerglings.
Source: http://wiki.teamliquid.net/starcraft/Patches_1.01-1.07

**Comment by gloomyson** [comment]
Fix your issue in 8431b9b
