### ISSUE TITLE
Publish it on GitHub Pages

### ISSUE THREAD

**Issue by IonicaBizau** [gloomyson/StarCraft#6]
You basically just need to create a branch named `gh-pages` from your `master` branch, then you can even delete the master branch and keep only the `gh-pages` branch since everything is client side. :smile: 

Awesome work! :sparkles:

**Comment by IonicaBizau** [comment]
After doing so, your app will be online at [`http://gloomyson.github.io/StarCraft`](http://gloomyson.github.io/StarCraft), and you will not need rawgit anymore, which anyway blocked the url because of too many requests.

**Comment by itay-grudev** [comment]
That is exactly what I was thinking for. @IonicaBizau though of it 13 minutes before I did, but you should definetely do that.

**Comment by IonicaBizau** [comment]
@itay-grudev  I guess only @gloomyson or other repository collaborators can do this. Basically its just the following:

```sh
$ git branch gh-pages
$ git push --all
```

To make the `gh-pages` branch the default one, go to [settings](https://github.com/gloomyson/StarCraft/settings/branches)–and select the `gh-pages` branch, then click the <kbd>Update</kbd> button.

Finally just `git push origin --delete  master`–to delete the `master` branch. :four_leaf_clover:

**Comment by akenn** [comment]
+1

**Comment by indus** [comment]
If you want starcraft.js.org as additional URL for free have a look at dns.js.org.

**Comment by tomchentw** [comment]
When checkout `gh-pages` branch, add `--orphan` tag to it. It's because your deployed assets should contain as minimal files as possible, so it could be very different from your master branch.

**Comment by josephmilla** [comment]
+1 Then, point it to a dope ass domain. I'm interested in improving this project. Let's make the UI/UX better! Add more features too? :heart:

**Comment by GaiusCoffee** [comment]
:+1:

**Comment by IonicaBizau** [comment]
Until then, [here we go!](https://cdn.rawgit.com/gloomyson/StarCraft/master/index.html). RawGit has the cdn option which is not blocked. :smile:

**Comment by pjc0247** [comment]
:+1:

**Comment by yaroslavya** [comment]
Got stuck on now loading in both ff and chrome. Tried here: https://cdn.rawgit.com/gloomyson/StarCraft/master/index.html

**Comment by CKing** [comment]
running on [my](http://sc.paars-gaming.de/) server, git pull is on a weekly cron.
have fun!

**Comment by omnidan** [comment]
:+1: publishing it on `gh-pages` and linking to that in the README.md would be nice

**Comment by CKing** [comment]
not so easy, as this project currently uses assets, which are under copyright from blizzard.
it is better to host these things under a different server and maybe link it from here.
this is the reason i set up a clone of this repo under http://sc.paars-gaming.de

**Comment by IonicaBizau** [comment]
> as this project currently uses assets, which are under copyright from blizzard.

I think that if Blizzard will not like this project, they have the power of shutting it down anyway (see [GitHub dmca](https://github.com/github/dmca))–the assets are already on GitHub. Personally, from this point of view, I don't see the difference between having them published on GitHub pages or just like it is now–it's just a branch name in fact. :smile:

**Comment by IonicaBizau** [comment]
But who knows, maybe in the end @gloomyson will get a job offer from Blizzard. :smile_cat:

**Comment by CKing** [comment]
Well, you can remove assets from the git history.

**Comment by gloomyson** [comment]
I'll added gh-pages branch, you can check out how it works.
