### ISSUE TITLE
No sounds in Safari

### ISSUE THREAD

**Issue by fleshman** [gloomyson/StarCraft#9]
There are no sounds when using safari, neither in iOS nor in OSX.

**Comment by gloomyson** [comment]
I guess Safari doesn't support wav format audio is the root cause, to hear sound, need to change all audio files under bgm to mp3 format which is more compatible.

**Comment by josephmilla** [comment]
I would suggest using Chrome

**Comment by gloomyson** [comment]
Currently you can use Chrome instead...
